/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3t4K3zm900R
 */
import { useState } from 'react';
import { Button } from "@/app/components/ui/button";
import { TicketProps } from '../types/common';

interface RegCounterProps {
    session: string;
    tickets: TicketProps[];
}
export const RegCounter: React.FC<RegCounterProps> = ({ session, tickets }) => {
    const [totalTickets, setTotalTickets] = useState(0);

    const add = (index: number) => {
        if (totalTickets < 25) {
            const updatedTickets = [...tickets];
            updatedTickets[index].qty += 1;
            setTotalTickets((prevTotal) => prevTotal + 1);
        }
    };

    const remove = (index: number) => {
        if (tickets[index].qty > 0) {
            const updatedTickets = [...tickets];
            updatedTickets[index].qty -= 1;
            setTotalTickets((prevTotal) => prevTotal - 1);
        }
    };
    const hasOnlyJuniorOrInfant = () => {
        const selectedTickets = tickets.filter((ticket) => ticket.qty > 0);
        const juniorOrInfantCount = selectedTickets.filter(
            (ticket) => ticket.name === 'Junior' || ticket.name === 'Infant'
        ).length;
        return juniorOrInfantCount === selectedTickets.length;
    };
    
    const reviewTickets = () => {
        const selectedTickets = tickets.filter((ticket) => ticket.qty > 0);
        console.log('Selected Tickets:', selectedTickets);
    };

    return (
        <div className="mx-auto w-full">
            <h1 className="text-1xl font-semibold mb-3">Select tickets</h1>
            <div className="border rounded-lg overflow-hidden">
                {tickets.map((ticket, index) => (
                    <div key={index} className="flex items-center justify-between p-4 border-b">
                        <span className="text-lg">{ticket.name}</span>
                        <div className="flex items-center">
                            <Button onClick={() => remove(index)} className="bg-white text-black border">
                                -
                            </Button>
                            <div className="w-[40px] flex justify-center py-2 bg-gray-700 text-white">{ticket.qty}</div>
                            <Button
                                onClick={() => add(index)}
                                className={`bg-white text-black border ${totalTickets === 25 ? 'opacity-50 cursor-not-allowed' : ''}`}
                                disabled={totalTickets === 25}
                            >
                                +
                            </Button>
                        </div>
                    </div>
                ))}
            </div>
            <Button
                className="w-full bg-gray-700 rounded text-white py-3 mt-6"
                onClick={reviewTickets}
                disabled={totalTickets === 0 || hasOnlyJuniorOrInfant()}
            >
                Review Tickets
            </Button>
        </div>
    );
}
