/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3D87LMoz6DE
 */
import { OrderDetailProps } from "../types/order"
import { formatDate } from "../lib/formattedDate";
import { timerAtom } from "../states/order";
import { useAtomValue } from "jotai";

export function OrderReviewCard({ info, details }: OrderDetailProps) {
  const timer = useAtomValue(timerAtom);
  const fees = details.fees;
  const tickets = details.tickets;
  return (
    // <div className="bg-white rounded-lg shadow-md w-[315px]">
    <div className="bg-white rounded-lg shadow-md w-full">
      <div className="flex items-center gap-2 justify-start border-b p-4">
        <ClockIcon className="text-gray-500" />
        <div className="text-sm">
        <span className="font-semibold">{timer} mins</span> remaining
        </div>
      </div>
      <div className="bg-gray-50 p-4 rounded-lg width-full">
        <div className="text-sm text-gray-600">{info.location}</div>
        {/* <div className="text-sm text-gray-600">Event Date: Tue, Feb 13, 2024</div> */}
        <div className="text-sm text-gray-600">{formatDate(info.date, info.timezone, 'ccc, LLL dd, yyyy')}</div>
        {/* <div className="text-sm text-gray-600">Event Arrival: 6:00 PM</div> */}
        <div className="text-sm text-gray-600">{info.arrival}</div>
      </div>
      <div className="pt-4 px-4">
        <div className="text-lg font-semibold">General Admission</div>
        {tickets.map((ticket, index) => (
          <div key={index} className="flex justify-between py-2 border-b">
            <div>{`${ticket.qty} × ${ticket.name}`}</div>
            <div>{`$${Number(ticket.currency_amount).toFixed(2)}`}</div>
          </div>
        ))}
        {/* <div className="flex items-center justify-between py-2">
          <div className="text-sm">Apply a promo code</div>
          <PlusIcon className="text-gray-500" />
        </div> */}
      </div>
      <div className="bg-gray-50 pt-4 px-4 rounded-b-lg">
        <div className="flex justify-between border-b pb-2">
          <div>Subtotal</div>
          <div>{`$${Number(fees.subtotal).toFixed(2)}`}</div>
        </div>
        <div className="flex justify-between py-2">
          <div>Facility Fee</div>
          <div>{`$${Number(fees.facility_fee).toFixed(2)}`}</div>
        </div>
        <div className="flex justify-between py-2 border-b">
          <div>Tax</div>
          <div>{`$${Number(fees.tax).toFixed(2)}`}</div>
        </div>
        <div className="flex justify-between py-4">
          <div className="text-lg font-semibold">Order Total</div>
          <div className="text-lg font-semibold">{`$${Number(fees.total).toFixed(2)}`}</div>
        </div>
      </div>
    </div>
  )
}


function ClockIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 16 14" />
    </svg>
  )
}


function PlusIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
