// DEV CONFIG

module.exports = {
    ENCHANT_API: "https://ticketing-api-dev.enchantlabs.io",
    WAIVERS_API: "https://waivers-api-dev.enchantlabs.io",
    TICKETURE_CACHE_API: "https://enchant.tix-web.d1tix.com",
    TICKETURE_API: "https://api.d1tix.com",
    SEGMENT_KEY: "Nt2fI3Ptn9VuOeXbf7CJyGWwi9zAZpmR",
    STRIPE: "pk_test_TleZZGKyHAie39VDmUzumqZ1",
    STRIPE_ACCOUNT: "acct_1LSoGhRK9ChhkYpq",
    MY_ACCOUNT: "https://my.enchantchristmas.com/magic-link-access",
    CITIES: [
      {
        city: "Kansas City, KS",
        venueName: "Legends Field",
        id: "0188d62c-92ca-5333-0454-e5dfdbe08c10",
        timezone: "America/Chicago",
        key: "kansas-city-ks-legends-field",
        theme: "tme",
        code: "ksc",
        stripeAccount: "acct_1LSoGhRK9ChhkYpq",
      },
      {
        city: "Las Vegas, NV",
        venueName: "Las Vegas Ballpark®",
        id: "0188d637-b4ba-0b97-c997-0570772f6f4d",
        timezone: "America/Los_Angeles",
        key: "las-vegas-nv-ballpark",
        theme: "tme",
        code: "lvs",
        stripeAccount: "acct_1LSoGhRK9ChhkYpq",
      },
      {
        city: "Milwaukee, WI",
        venueName: "Franklin Field",
        id: "0188d638-566f-a486-1c62-c2ad1d71db2a",
        timezone: "America/Chicago",
        key: "milwaukee-wi-franklin-field",
        theme: "tgs",
        code: "mke",
        stripeAccount: "acct_1LSoGhRK9ChhkYpq",
      },
      {
        city: "San Jose, CA",
        venueName: "PayPal Park",
        id: "0188db18-1959-e809-795f-8c825757237c",
        timezone: "America/Los_Angeles",
        key: "san-jose-ca-paypal-park",
        theme: "tgs",
        code: "sjo",
        stripeAccount: "acct_1LSoGhRK9ChhkYpq",
      },
      {
        city: "Scottsdale, AZ",
        venueName: "Salt River Fields",
        id: "0188db16-c8b8-3d6c-9725-e20dbb1b2cc3",
        timezone: "America/Los_Angeles",
        key: "scottsdale-az-salt-river-fields",
        theme: "tgs",
        code: "sco",
        stripeAccount: "acct_1LSoGhRK9ChhkYpq",
      },
      {
        city: "St. Petersburg, FL",
        venueName: "Tropicana Field",
        id: "0188db19-2792-6885-f200-1877f33f140f",
        timezone: "America/New_York",
        key: "st-petersburg-fl-tropicana-field",
        theme: "trg",
        code: "stp",
        stripeAccount: "acct_1LSoGhRK9ChhkYpq",
      },
      {
        city: "Washington, DC",
        venueName: "Nationals Park",
        id: "0188db13-48af-ca00-bea4-2af061d2e396",
        timezone: "America/New_York",
        key: "washington-dc-nationals-park",
        theme: "trg",
        code: "wdc",
        stripeAccount: "acct_1LSoGhRK9ChhkYpq",
      },
    ],
  };
  
  // PROD CONFIG
  
  // module.exports = {
  //   ENCHANT_API: "https://ticketing-api.enchantchristmas.com",
  // 	WAIVERS_API: "https://waivers-api.enchantchristmas.com",
  //   TICKETURE_CACHE_API: "https://tix.enchantchristmas.com",
  //   TICKETURE_API: "https://api.ticketure.com",
  // 	SEGMENT_KEY: "6zABWKEGSJn01Y02cyyEyZnwzRd0xqaG",
  //   STRIPE: "pk_live_jjj8qApU74r1UeiiGHEDEjrB",
  //   STRIPE_ACCOUNT: "acct_1MxwN7RNNqaVZ1Ou",
  //   MY_ACCOUNT: "https://my.enchantchristmas.com/magic-link-access",
  //   MY_ACCOUNT_DEV: "https://my-dev.enchantlabs.io/magic-link-access",
  // CITIES: [
  //     {
  //       city: "Kansas City, KS",
  //       venueName: "Legends Field",
  //       id: "ff61d20d-d95e-b9d5-c4a1-cc485222952b",
  //       timezone: "America/Chicago",
  //       key: "kansas-city-ks-legends-field",
  //       theme: "tme",
  //       code: "ksc",
  // 			stripeAccount: "acct_1Ncyi4IcoaWJRuLI",
  //     },
  //     {
  //       city: "Las Vegas, NV",
  //       venueName: "Las Vegas Ballpark®",
  //       id: "018242b6-e751-cf61-4b7b-ca1c36ca1a54",
  //       timezone: "America/Los_Angeles",
  //       key: "las-vegas-nv-ballpark",
  //       theme: "tme",
  //       code: "lvs",
  // 			stripeAccount: "acct_1MxwN7RNNqaVZ1Ou",
  //     },
  //     {
  //       city: "Milwaukee, WI",
  //       venueName: "Franklin Field",
  //       id: "67642c97-4c14-daeb-a602-8b2c61bf0fcf",
  //       timezone: "America/Chicago",
  //       key: "milwaukee-wi-franklin-field",
  //       theme: "tgs",
  //       code: "mke",
  // 			stripeAccount: "acct_1NcygsRAi8qERXID",
  //     },
  //     {
  //       city: "San Jose, CA",
  //       venueName: "PayPal Park",
  //       id: "018242b4-440c-189b-a8b9-fa60823997bc",
  //       timezone: "America/Los_Angeles",
  //       key: "san-jose-ca-paypal-park",
  //       theme: "tgs",
  //       code: "sjo",
  // 			stripeAccount: "acct_1MxwN7RNNqaVZ1Ou",
  //     },
  //     {
  //       city: "Scottsdale, AZ",
  //       venueName: "Salt River Fields",
  //       id: "018242af-4e9a-01a6-60f4-d15e51fba312",
  //       timezone: "America/Los_Angeles",
  //       key: "scottsdale-az-salt-river-fields",
  //       theme: "tgs",
  //       code: "sco",
  // 			stripeAccount: "acct_1MxwN7RNNqaVZ1Ou",
  //     },
  //     {
  //       city: "St. Petersburg, FL",
  //       venueName: "Tropicana Field",
  //       id: "0182428c-678f-8198-86d9-66a467fc4d9c",
  //       timezone: "America/New_York",
  //       key: "st-petersburg-fl-tropicana-field",
  //       theme: "smt",
  //       code: "stp",
  // 			stripeAccount: "acct_1MxwN7RNNqaVZ1Ou",
  //     },
  //     {
  //       city: "Washington, DC",
  //       venueName: "Nationals Park",
  //       id: "de1bd25f-646e-da49-46ed-f39267fac753",
  //       timezone: "America/New_York",
  //       key: "washington-dc-nationals-park",
  //       theme: "tgs",
  //       code: "wdc",
  // 			stripeAccount: "acct_1MxwN7RNNqaVZ1Ou",
  //     },
  //   ],
  // };